apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\usr\local\bin\kompose.exe convert -o ./.k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
