version: '3'

services:

  frontend:
    container_name: node-service-jumpstart
    image: node-service-jumpstart
    build:
      context: .
      dockerfile: .docker/node.dockerfile
    environment:
      - NODE_ENV=production
      - CONTAINER=true
    ports:
      - "4200:4200"
    # networks:
    #  - app-network

#networks:
#  app-network:
#    driver: bridge